"""init

Revision ID: 92e9c9214e36
Revises: 
Create Date: 2021-03-26 13:59:14.436756

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '92e9c9214e36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.Column('assignee_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('priority', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('status', sa.String(length=255), nullable=False),
                    sa.Column('grade', sa.Float(), nullable=True),
                    sa.Column('due_date', sa.DateTime(), nullable=False),
                    sa.Column('completion_date', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('creator_id', 'assignee_id', 'name', name='_task_names_uc'),
                    sa.UniqueConstraint('creator_id', 'assignee_id', 'priority', name='_task_priorities_uc')
                    )
    op.create_index(op.f('ix_tasks_assignee_id'), 'tasks', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_tasks_creator_id'), 'tasks', ['creator_id'], unique=False)
    op.create_table('task_notes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('task_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_task_notes_user_id'), 'task_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_notes_user_id'), table_name='task_notes')
    op.drop_table('task_notes')
    op.drop_index(op.f('ix_tasks_creator_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assignee_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
