version: "3.3"
services:
  auth_service:
    depends_on:
      - postgres-auth
    build:
      context: ./auth_service/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - POSTGRES_HOST=172.28.0.3
    networks:
      web:
        ipv4_address: 172.28.0.2
    ports:
      - 8001:8001
  postgres-auth:
    image: postgres:13
    networks:
      web:
        ipv4_address: 172.28.0.3
    ports:
      - 5433:5432
    volumes:
      - db-auth-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - PGDATA=/var/lib/postgresql/data
  metrics_service:
    depends_on:
      - postgres-metrics
      - auth_service
    build:
      context: ./metrics_service/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - POSTGRES_HOST=172.28.0.5
      - AUTH_API_URL=172.28.0.2:8001
    networks:
      web:
        ipv4_address: 172.28.0.4
    ports:
      - 8002:8002
  postgres-metrics:
    image: postgres:13
    networks:
      web:
        ipv4_address: 172.28.0.5
    ports:
      - 5434:5432
    volumes:
      - db-metrics-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - PGDATA=/var/lib/postgresql/data
  task_service:
    depends_on:
      - postgres-tasks
      - auth_service
    build:
      context: ./task_service/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - POSTGRES_HOST=172.28.0.7
      - AUTH_API_URL=172.28.0.2:8001
    networks:
      web:
        ipv4_address: 172.28.0.6
    ports:
      - 8003:8003
  postgres-tasks:
    image: postgres:13
    networks:
      web:
        ipv4_address: 172.28.0.7
    ports:
      - 5435:5432
    volumes:
      - db-tasks-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gym_master
      - POSTGRES_PASSWORD=threehundredbucks
      - POSTGRES_DB=dungeon
      - PGDATA=/var/lib/postgresql/data
networks:
  web:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
volumes:
  db-auth-volume:
    external: true
  db-metrics-volume:
    external: true
  db-tasks-volume:
    external: true
