"""responsible_users

Revision ID: d89c543c4f2a
Revises: 6ce6a6ab9cd0
Create Date: 2021-04-26 13:47:50.502385

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd89c543c4f2a'
down_revision = '6ce6a6ab9cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible_users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('building_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('buildings', sa.Column('address', sa.String(), nullable=True))
    op.add_column('buildings', sa.Column('building_index', sa.String(), nullable=True))
    op.add_column('buildings', sa.Column('building_type', sa.String(), nullable=True))
    op.add_column('buildings', sa.Column('construction_year', sa.Integer(), nullable=True))
    op.add_column('buildings', sa.Column('description', sa.String(), nullable=True))
    op.add_column('buildings', sa.Column('last_capital_repair_year', sa.Integer(), nullable=True))
    op.add_column('buildings', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_buildings_building_type'), 'buildings', ['building_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_buildings_building_type'), table_name='buildings')
    op.drop_column('buildings', 'name')
    op.drop_column('buildings', 'last_capital_repair_year')
    op.drop_column('buildings', 'description')
    op.drop_column('buildings', 'construction_year')
    op.drop_column('buildings', 'building_type')
    op.drop_column('buildings', 'building_index')
    op.drop_column('buildings', 'address')
    op.drop_table('responsible_users')
    # ### end Alembic commands ###
