"""personnel

Revision ID: 0f59f583aea6
Revises: b3832690cb3c
Create Date: 2021-04-30 12:44:55.972197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f59f583aea6'
down_revision = 'b3832690cb3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('living_quantity', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('studying_daytime', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('studying_evening_time', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('studying_part_time', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('working_help', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('working_science', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('working_teachers', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_sensor_meter_uc', 'meter_sensor_binding', ['sensor_id', 'meter_id'])
    op.create_unique_constraint('_coordinates_uc', 'locations', ['longitude', 'latitude'])
    op.create_unique_constraint('devices_secret_key_key', 'devices', ['secret_key'])
    op.create_unique_constraint('devices_recognition_key_key', 'devices', ['recognition_key'])
    op.drop_column('buildings', 'working_teachers')
    op.drop_column('buildings', 'working_science')
    op.drop_column('buildings', 'working_help')
    op.drop_column('buildings', 'studying_part_time')
    op.drop_column('buildings', 'studying_evening_time')
    op.drop_column('buildings', 'studying_daytime')
    op.drop_column('buildings', 'living_quantity')
    # ### end Alembic commands ###
