"""init

Revision ID: 296bd57e715e
Revises: 
Create Date: 2021-02-14 19:12:10.057991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296bd57e715e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(length=255), nullable=True),
    sa.Column('metric_type', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=31), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    # ### end Alembic commands ###
