"""device_types

Revision ID: 2de68e6e8a30
Revises: 0f59f583aea6
Create Date: 2021-04-30 13:01:09.507351

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '2de68e6e8a30'
down_revision = '0f59f583aea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_types',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.add_column('devices', sa.Column('device_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'devices', 'device_types', ['device_type_id'], ['id'])
    op.drop_column('devices', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_sensor_meter_uc', 'meter_sensor_binding', ['sensor_id', 'meter_id'])
    op.create_unique_constraint('_coordinates_uc', 'locations', ['longitude', 'latitude'])
    op.add_column('devices', sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_unique_constraint('devices_secret_key_key', 'devices', ['secret_key'])
    op.create_unique_constraint('devices_recognition_key_key', 'devices', ['recognition_key'])
    op.drop_column('devices', 'device_type_id')
    op.drop_table('device_types')
    # ### end Alembic commands ###
