"""cascading

Revision ID: 1efc6098793f
Revises: 2de68e6e8a30
Create Date: 2021-05-01 12:30:42.620532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efc6098793f'
down_revision = '2de68e6e8a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('building_rooms_building_id_fkey', 'building_rooms', type_='foreignkey')
    op.create_foreign_key(None, 'building_rooms', 'buildings', ['building_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('devices_room_id_fkey', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'building_rooms', ['room_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('readings_device_id_fkey', 'readings', type_='foreignkey')
    op.create_foreign_key(None, 'readings', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'readings', type_='foreignkey')
    op.create_foreign_key('readings_device_id_fkey', 'readings', 'devices', ['device_id'], ['id'])
    op.create_unique_constraint('_sensor_meter_uc', 'meter_sensor_binding', ['sensor_id', 'meter_id'])
    op.create_unique_constraint('_coordinates_uc', 'locations', ['longitude', 'latitude'])
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key('devices_room_id_fkey', 'devices', 'building_rooms', ['room_id'], ['id'])
    op.create_unique_constraint('devices_secret_key_key', 'devices', ['secret_key'])
    op.create_unique_constraint('devices_recognition_key_key', 'devices', ['recognition_key'])
    op.drop_constraint(None, 'building_rooms', type_='foreignkey')
    op.create_foreign_key('building_rooms_building_id_fkey', 'building_rooms', 'buildings', ['building_id'], ['id'])
    # ### end Alembic commands ###
