# Generated by Django 3.1.4 on 2021-04-22 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(db_index=True, max_length=255)),
                ('entity_id', models.IntegerField()),
                ('permission_set', models.JSONField(default=list)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usergroup')),
            ],
            options={
                'index_together': {('entity_type', 'entity_id')},
            },
        ),
    ]
